# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - se-usermanagement

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_dda50975622c4d2a843c3f89fc782a80 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4f69dcb25ae847a1959d921b85cedb4c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_dda50975622c4d2a843c3f89fc782a80 }}/jerreeey/spring:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'se-usermanagement'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f0610f5ca2d446888ee3b82d4f28dbe1 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_dda50975622c4d2a843c3f89fc782a80 }}/jerreeey/spring:${{ github.sha }}'